[package]
name = "felay-gui"
version = "0.1.0"
description = "Felay â€” Feishu CLI Proxy GUI"
authors = ["zqq"]
license = "LicenseRef-SEE-LICENSE"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
